{ inputs, ... }:
{
  imports = [
    inputs.agenix.nixosModules.default
    inputs.home-manager.nixosModules.home-manager
    inputs.nixos-mailserver.nixosModules.default
    inputs.nixvim.nixosModules.nixvim
    ./backup.nix
    ./desktop-env.nix
    ./django-svelte.nix
    ./django.nix
    ./fail2ban.nix
    ./fastapi-svelte.nix
    ./fastapi.nix
    ./glesys-updaterecord.nix
    ./hm.nix
    ./ide.nix
    ./mail-client.nix
    ./mailserver.nix
    ./mysql.nix
    ./nginx.nix
    ./nix.nix
    ./postgresql.nix
    ./shell.nix
    ./svelte.nix
    ./system.nix
    ./user.nix
    ./vd.nix
    ./wireguard.nix
    ./wordpress.nix
  ];
}
